const message = {
    CATEGORY_CREATED: "Category has been created successfully",
    INVALID_CATEGORY_ID: "Please provide a valid category ID",
    NO_CATEGORY_ID: "Please provide category ID",
    INVALID_CATEGORY_CREATION: "Only admin can create a category",
    NO_CATEGORY: "Category not found",
    CATEGORY_UPDATED: "Category has been updated successfully",
    INVALID_CATEGORY_UPDATION: "Only admin can update category",
    INVALID_CATEGORY_DELETION: "Only admin can delete a category",
    CATEGORY_DELETED: "Category has been deleted successfully",
    INVALID_CATEGORY_IDS: "Please provide valid category IDs",
    BULK_CATEGORIES_DELETE: "Selected categories have been deleted successfully",
    NO_CATEGORIES: "Selected categories do not exist",
    NO_BULK_CATEGORIES: "Selected categories not found",
    INVALID_FORMAT: "IDs should be an array in bulk delete",
    NO_SELECTED_CATEGORY: "Please select at least one category to proceed",
    FAQ_CREATED: "FAQ has been created successfully",
    INVALID_FAQ_ID: "Please provide a valid FAQ ID",
    NO_FAQ_ID: "Please provide FAQ ID",
    INVALID_FAQ_CREATION: "Only admin can create an FAQ",
    NO_FAQ: "FAQ not found",
    FAQ_UPDATED: "FAQ has been updated successfully",
    INVALID_FAQ_UPDATION: "Only admin can update FAQ",
    INVALID_FAQ_DELETION: "Only admin can delete FAQ",
    FAQ_DELETED: "FAQ has been deleted successfully",
    INVALID_FAQ_IDS: "Please provide valid FAQ IDs",
    BULK_FAQ_DELETE: "Selected FAQs have been deleted successfully",
    NO_BULK_FAQ: "Selected FAQs not found",
    NO_SELECTED_FAQ: "Please select at least one FAQ to proceed",
    LOGIN: "User logged in successfully",
    INVALID_PASSWORD: "Incorrect password",
    SIGNED_UP: "User has been registered successfully",
    USER_NOT_EXIST: "User does not exist",
    INTERNAL_ERROR: "An error occurred! Please try again",
    REGISTRATION_ERROR: "User could not register! Try again",
    USER_EXISTS: "Email already exists! Try another",
    JWT_ENC_ERROR: "Password encryption failed! Try again",
    NO_TOKEN: "Authorization token is required to proceed",
    INVALID_TOKEN: "Invalid Token",
    INVALID_AUTH: "Only admin can create, edit, or delete categories",
    SECRET_KEY_ERROR: "Secret key not found"
};
module.exports = message